version: "3.0"


services:
  dj_1:
    container_name: dj_s
    build:
      context: ./dj_server
    ports:
      - "8080:8000"
    command: >
      sh -c "./runner.sh"
  dj_2:
    container_name: dj_c
    build:
      context: ./dj_client
    ports:
      - "8060:8000"
    command: >
      sh -c "./runner.sh"