# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import question_pb2 as question__pb2


class QuizStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuestion = channel.unary_unary(
                '/question.Quiz/GetQuestion',
                request_serializer=question__pb2.QuestionRequest.SerializeToString,
                response_deserializer=question__pb2.QuestionResponse.FromString,
                )


class QuizServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuizServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestion,
                    request_deserializer=question__pb2.QuestionRequest.FromString,
                    response_serializer=question__pb2.QuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'question.Quiz', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Quiz(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/question.Quiz/GetQuestion',
            question__pb2.QuestionRequest.SerializeToString,
            question__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
