# Generated by Django 4.0.4 on 2022-04-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=5)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
